name: backport.yml
on:
  #  pull_request:
  #    types: [ closed ]
  pull_request_target:
    types: [ labeled, closed ]

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # důležité pro cherry-pick

      - name: Fetch PR branch
        run: |
          git fetch origin main
          git fetch origin pull/${{ github.event.pull_request.number }}/head:backport
          echo "origin pull/${{ github.event.pull_request.number }}/head:backport"
          COMMITS=$(git log --format="%H" origin/main..backport)
          echo "$COMMITS"
          echo "$COMMITS" > commits.txt

      ## bude ten commit vždy jen jeden??
      - name: Cherry-pick to backport branch
        run: |
          git checkout prod
          file="commits.txt"
          while read -r line; do
            echo "$line"
            git cherry-pick "$line" || git cherry-pick --abort
          done <$file