name: backport.yml
on:
  #  pull_request:
  #    types: [ closed ]
  pull_request_target:
    types: [ labeled, closed ]

jobs:
  backport:
    if:  github.event.pull_request.merged && contains(github.event.label.name, 'backport')
    #      (
    #        github.event_name == 'pull_request' &&
    #        github.event.pull_request.merged == true &&
    #        contains(github.event.pull_request.labels.*.name, 'backport')
    #      ) ||
    #      (
    #        github.event_name == 'pull_request_target' &&
    #        github.event.pull_request.state == 'closed' &&
    #        contains(github.event.label.name, 'backport')
    #      )

    runs-on: ubuntu-latest
    steps:
      # tree pro případ více různých sustaining label -> kam ten commit pujde
      - name: Echo
        run: |
          echo "HELLO"