name: backport-reuse.yml
on:
  pull_request_target:
    types: ["closed", "labeled"]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    uses: pepepopo-bot/workflows/.github/workflows/backport-workflow.yml@main
    with:
      event: ${{ github.event.action }}
      label: ${{ github.event.action == 'labeled' && github.event.label.name || '' }}
      pull_request: ${{ toJSON(github.event.pull_request) }}