name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
        include:
          - java: 17
            sonar: true
    name: "Java ${{ matrix.java }} build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
          cache: "maven"
      - name: Verify build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          MAVEN_ARGS="verify"
          if [[ "${{ matrix.sonar }}" == "true" ]]; then
            MAVEN_ARGS="$MAVEN_ARGS -P metrics sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo"
          fi
          mvn $MAVEN_ARGS

