name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    name: "Java build"
    steps:
      - name: 'Test for Sonar secret'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            echo "SONAR_TOKEN_SET=$(test ${SONAR_TOKEN} && echo true)" >> $GITHUB_ENV
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Check
        run: mvn -B -P metrics install

      - name: Sonar
        if: env.SONAR_TOKEN_SET == 'true'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo

      - name: Save PR info
        if: env.SONAR_TOKEN_SET != 'true'
        run: |
          echo "PR_NUMBER= ${{ github.event.pull_request.number }}" > pr_metadata.txt
          echo "PR_BRANCH= ${{ github.head_ref }}" > pr_metadata.txt
          echo "PR_BASE= ${{ github.base_ref }}" > pr_metadata.txt

      - name: Upload PR info
        if: env.SONAR_TOKEN_SET != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pr_info
          path: pr_info.txt

      - name: Upload Java binaries for Sonar
        if: env.SONAR_TOKEN_SET != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            **/target