name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    name: "Java ${{ matrix.java }} build"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
          cache: "maven"
      - name: Check
        run: mvn -B verify
      - name: Check latest during push
        if: matrix.java == '17' && github.event_name == 'push'
        run: mvn -B -P metrics verify
      - name: Test lastest during push
        if: matrix.java == '17' && github.event_name == 'push'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -=pepepopo-bot_test_repo