name: build_pr.yml
on:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: "Java ${{ matrix.java }} build"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-#jmeno vlastnika PR
          restore-keys: ${{ runner.os }}-m2

      - name: Check 11
        run: mvn -B verify

      - name: Check 17
        run:
          # použít matrix pro přidání parametru

      - name: Upload binaries and tst results
        uses: actions/upload-artifact
        with:
          name: target
          path: |
            **/target
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: offline mode
        run: mvn dependency:go-offline
      - name: checkout ref PR
        uses:
          with

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run : |
          mvn -o sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo \
          -Dsonar.java.binaries= **/* \
          -Dsonar.pullrequest.
          
