name: Sonar

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
      actions: read
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Java binaries
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          repo: pepepopo-bot/test_repo
          github_token: ${{ secrets.PAT }}
          allow_forks: true
          name: compiled
          path: compiled
          workflow_search: true

      - name: Get PR info
        run: |
          set -e
          
          PR_URL=$(jq -r '.workflow_run.pull_requests[0].url' "$GITHUB_EVENT_PATH")
          
          PR_JSON=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "$PR_URL")
          
          echo "pr_number=$(echo "$PR_JSON" | jq -r '.number')" >> $GITHUB_OUTPUT
          echo "pr_branch=$(echo "$PR_JSON" | jq -r '.head.ref')" >> $GITHUB_OUTPUT
          echo "pr_base=$(echo "$PR_JSON" | jq -r '.base.ref')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: SonarCloud Scan on PR
        if: github.event.workflow_run.event == 'pull_request'
        run: mvn sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo -Dsonar.java.binaries=**/* -Dsonar.pullrequest.key=${{ steps.get-pr-info.outputs.pr_number }} -Dsonar.pullrequest.branch=${{ steps.get-pr-info.outputs.pr_branch }} -Dsonar.pullrequest.base=${{ steps.get-pr-info.outputs.pr_base }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}