name: Sonar analysis
on:
  workflow_run:
    workflows: ["Sonar"]
    types: [completed]

## bot account pro PAT??
jobs:
  sonar:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      ## PR info je  asi lepší získat GH api-> no ale na to taky potřebuju přenést PR number info
      - name: download PR info
        uses: actions/download-artifact@v4
        with:
          name: pr-event-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: download build artefacts
        uses: actions/download-artifact@v4
        with:
          name: compiled
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: save PR info in to env
        shell: bash
        run: |
          echo "pr_number=$(sed '1q;d' pr-event.txt)" >> "$GITHUB_ENV"
          echo "pr_head_ref=$(sed '1q;d' pr-event.txt)" >> "$GITHUB_ENV"
          echo "pr_base_ref=$(sed '1q;d' pr-event.txt)" >> "$GITHUB_ENV"
          echo "pr_head_sha=$(sed '1q;d' pr-event.txt)" >> "$GITHUB_ENV"

      - name: checkout head branch
        uses: actions/checkout@v4
        with:
          repository: '${{ github.event.workflow_run.head_repository.full_name  }}'
          ref: ${{ github.event.workflow_run.head_sha}}
          fetch-depth: '0'

      - name: checkout base branch
        run: |
          git remote add upstream https://github.com/pepepopo-bot/test_repo
          git fetch upstream
          git checkout -B $pr_base_ref upstream/$pr_base_ref
          git checkout ${{ github.event.workflow_run.head_sha }}
          git clean -ffdx && git reset --hard HEAD

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          # předávat versi jako latest pro test pr-event.txt ??
          version: '17'
          distribution: 'temurine'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo \
          -Dsonar.java.binaries=**/* \
          -Dsonar.pullrequest.key=${{ steps.pr_number.outputs.content }} \
          -Dsonar.pullrequest.branch=${{ env.PR_HEAD_BRANCH }} \
          -Dsonar.pullrequest.base=${{ env.PR_BASE_BRANCH }}