name: Sonar

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH

      - name: Download Java binaries
        uses: actions/download-artifact@v4
        with:
          name: java-binaries
          path: java-binaries

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: List Java binaries
        run: ls -R binaries

      - name: SonarCloud Scan on PR
        if: github.event.workflow_run.event == 'pull_request'
        run: mvn -X sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo -Dsonar.java.binaries=java-binaries/**/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
