name: Sonar

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Java binaries
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          repo: pepepopo-bot/test_repo
          github_token: ${{ secrets.PAT }}
          allow_forks: true
          name: compiled
          path: compiled
          workflow_search: true

      - name: List compiled folder
        run: ls -R compiled

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: SonarCloud Scan on PR
        if: github.event.workflow_run.event == 'pull_request'
        run: mvn -X sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo -Dsonar.java.binaries=target/classes -Dsonar.java.source=17
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
