name: Handle Maven analysis

on:
  workflow_call:
    inputs:
      java_version:
        description: Build Java version
        type: string
        default: "21"
      project_key:
        description: Target project key in SonarQube server
        type: string
        required: true
      workflow_run:
        description: Associated workflow_run event
        type: string
        required: true
    secrets:
      sonar_token:
        description: SonarQube analysis API token
        required: true

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare context
    outputs:
      pull_request: ${{ steps.export.outputs.pull_request }}
    steps:
      - name: Fetch pull_request
        uses: actions/download-artifact@v4
        with:
          name: pull_request
          run-id: ${{ fromJSON(inputs.workflow_run).id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export context values
        id: export
        shell: bash
        run: |
          if [ -f pull_request.json ]; then
            echo "pull_request=$(cat pull_request.json | jq -c .)" >> "$GITHUB_OUTPUT"
          fi
  analyze:
    name: Sonar analysis
    needs: prepare
    if: fromJSON(needs.prepare.outputs.pull_request).base.ref == 'main'
    uses: ./.github/workflows/sonar-maven.yml
    with:
      java_version: "${{ inputs.java_version }}"
      project_key: "${{ inputs.project_key }}"
      pull_request: "${{ needs.prepare.outputs.pull_request }}"
    secrets: inherit