name: Sonar

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  Sonar:
    name: Sonar
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
      actions: read
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Java binaries
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          repo: pepepopo-bot/test_repo
          github_token: ${{ secrets.PAT }}
          allow_forks: true
          name: compiled
          path: compiled
          workflow_search: true

      - name: Download PR number
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          repo: pepepopo-bot/test_repo
          github_token: ${{ secrets.PAT }}
          allow_forks: true
          name: pr_number
          path: .
          workflow_search: true

      - name: Read PR number
        id: pr_number
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pr_number.txt

      - name: Request GitHub API for PR data
        uses: octokit/request-action@v2.x
        id: get_pr_data
        with:
          route: GET /repos/${{ github.event.repository.full_name }}/pulls/${{ steps.pr_number.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save branches
        run: |
          PR_HEAD_BRANCH="${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}"
          PR_BASE_BRANCH="${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}"
    
          echo "PR_HEAD_BRANCH=$PR_HEAD_BRANCH" >> $GITHUB_ENV
          echo "PR_BASE_BRANCH=$PR_BASE_BRANCH" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: SonarCloud Scan on PR
        if: github.event.workflow_run.event == 'pull_request'
        run: mvn sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo -Dsonar.java.binaries=**/* -Dsonar.pullrequest.key=${{ steps.pr_number.outputs.content }} -Dsonar.pullrequest.branch=${{ env.PR_HEAD_BRANCH }} -Dsonar.pullrequest.base=${{ env.PR_BASE_BRANCH }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}