name: test.yml
on:
  pull_request:
    types: [ labeled, opened, closed, reopened ]
  push:

jobs:
  PR-message:
    env:
      PR-NUMBER: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: testMessage
        run: gh pr comment ${{ env.PR_NUMBER }} --body "Cannot cherrypick due to conflict."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}