name: test.yml
# nuné v cílovém repu povolit vytváření PR v gh actions!!!
on:
  pull_request_target:
    types: [labeled]

jobs:
  backport:
    if: github.event.label.name == 'backport'
    runs-on: ubuntu-latest
    permissions:
      # možna upravit práva
      contents: write
      pull-requests: write
    env:
      BACKPORT_TARGET_BRANCH: prod #branch kam chci přidat ty PR commity
      BACKPORT_BRANCH: backport/pr-${{ github.event.pull_request.number }} #nová branch pro push a vytvoreni PR
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BACKPORT_TARGET_BRANCH }}
          fetch-depth: 0
      # checkout target branch PR (main)
      # github.event.pull_request.head.sha is the right way to get SHA of the most recent commit before the pull request was closed.

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get PR commit SHAs
        run: |
          curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
            | jq -r '.[].sha' > commits.txt
          cat commits.txt
      # nelze dělat rozdíl větví, je nutné přes api získat jen commity toho PR

      - name: add message for conflict
        run: |
          git checkout -b ${{ env.BACKPORT_BRANCH }}
          while read -r sha; do
            git cherry-pick "$sha" || {
            echo "Conflict in $sha"
            git cherry-pick --abort
            exit 1
          }
          done < commits.txt

      - run: git push origin ${{ env.BACKPORT_BRANCH }}

      - run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
              --arg title "Backport #${{ github.event.pull_request.number }}" \
              --arg body "Automatický backport PR #${{ github.event.pull_request.number }}" \
              --arg head "${{ env.BACKPORT_BRANCH }}" \
              --arg base "${{ env.BACKPORT_TARGET_BRANCH }}" \
              '{title: $title, body: $body, head: $head, base: $base}')"
# možnost konfliktu
# ! [remote rejected] backport/pr-100 -> backport/pr-100 (refusing to allow a GitHub App to create or update workflow .github/workflows/test.yml without workflows permission) error: failed to push some refs to 'https://github.com/pepepopo-bot/test_repo' Error: Process completed with exit code 1.
# nejdou takto backportovat změny workflows -> gh token nemá právo workflows: write

#je toto použilené v případě, kdy už bylo PR merged a pak se přidá label?

#  ref: ${{ github.event.pull_request.head.sha }} use this insted of "refs/pull/${{ github.event.number }}/merge" -> raději volat fixed sha commit, menší riziko prohození kodu
# or Checkout refs/pull/${{ github.event.number }}/merge and then verify HEAD^ equals github.event.pull_request.head.sha
