name: test.yml
on:
  pull_request:
    types: [ labeled, opened, closed, reopened ]

jobs:
  PR-message:
    permissions: write-all
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
#      - name: testMessage
#        run: gh pr comment 93 --body "Cannot cherrypick due to conflict." --repo "pepepopo-bot/test_repo"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: API comment
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/pepepopo-bot/test_repo/pulls/$PR_NUMBER/comments \
            -d '{"body":"Great stuff!"}'
        env:
          PAT: ${{ secrets.PAT }}