name: Test

on:
  pull_request_target:
    types: [labeled, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Prepare parameters
    steps:
      - name: Prepare parameters
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name)
            const targets = labels
              .filter(l => l.startsWith("backport-"))
              .map(l => l.replace("backport-", ""))
            core.setOutput("targets", JSON.stringify(targets))
            console.out("targets")