name: test.yml

on:
  pull_request_target:
    types: [labeled]
    #types: [labeled, closed]
  workflow_dispatch:

jobs:
  backport:
    #if: github.event.label.name == 'backport' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # no pull-request: write
    env:
      BACKPORT_TARGET_BRANCH: prod #branch kam chci přidat ty PR commity
      BACKPORT_BRANCH: backport/pr-asd #nová branch pro push a vytvoreni PR
    steps:
      - name: Save BACKPORT_TARGET from label
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "${{ github.event.label.name }}"
          echo "startsWith(github.event.label.name, 'backport-')

      - run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
              --arg title "Backport #${{ github.event.pull_request.number }}" \
              --arg body "Automatický backport PR #${{ github.event.pull_request.number }}" \
              --arg head "${{ env.BACKPORT_BRANCH }}" \
              --arg base "${{ env.BACKPORT_TARGET_BRANCH }}" \
              '{title: $title, body: $body, head: $head, base: $base}')"
